### ISSUE TITLE
Queue.run() hogs a whole CPU

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/bunny-hook#7]
Something about the implementation of `Queue.run()` hogs an entire CPU, both locally and on the server, even when there's no work to be done. Here's what `run` looks like:

https://github.com/jeancochrane/bunny-hook/blob/8dd8d9f39d520beb8876d47b71501620e6ce4876/api/queue.py#L85-L96

This is bad, since running the queue is one of the two top-level processes necessary to run the app:

https://github.com/jeancochrane/bunny-hook/blob/8dd8d9f39d520beb8876d47b71501620e6ce4876/runqueue.py#L1-L9

I suspect that something is up with the way I'm handling connections in sqlite.

**Comment by kalilsn** [comment]
Addressed in #9
